### PR TITLE
Update docker build

### LINKED ISSUE #1113: Dockerfile compile error: object CRC32C is not a member of package java.util.zip
I'm trying to build Eclair in docker in [Simverse](https://github.com/darwin/simverse).

Git bisect pointed to 2f42538660779abf3f5594b670bb0b3632cb410a introduced compiler error `object CRC32C is not a member of package java.util.zip` [1].

It is probably caused by this: https://github.com/ACINQ/eclair/commit/2f42538660779abf3f5594b670bb0b3632cb410a#diff-094980f368988747a739b31df72815b8R19

I'm a Java noob. I tried to look for any changes in Dockerfiles on your side and didn't find anything where I got out of sync. Is this CRC32C a thing in older Java?

Observations:
1. Running `docker build .` from [tip](74af0304bd87f5cec93841d5181caffe3dfdb85d) of the eclair repo, fails in the same way
2. DockerHub CI builds [work](https://travis-ci.org/ACINQ/eclair/builds/578695813), because (I assume) they run on top of Java 11

[1] https://travis-ci.org/darwin/simverse/builds/578231444#L7799-L7805

### PR DESCRIPTION
**Pull request by araspitzu**
Update the docker build to use maven 3.6.2 and JDK11 base images, fixes #1113

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -1,14 +1,13 @@
...
+FROM adoptopenjdk/openjdk11:jdk-11.0.3_7-alpine as BUILD
 
 # Setup maven, we don't use https://hub.docker.com/_/maven/ as it declare .m2 as volume, we loose all mvn cache
 # We can alternatively do as proposed by https://github.com/carlossg/docker-maven#packaging-a-local-repository-with-the-image
 # this was meant to make the image smaller, but we use multi-stage build so we don't care
-
 RUN apk add --no-cache curl tar bash
 
-ARG MAVEN_VERSION=3.6.0
+ARG MAVEN_VERSION=3.6.2
```
Comment (t-bast) [inline Dockerfile]: Isn't it maven 3.6.1 that is the latest recommended version?

**Comment by araspitzu** [comment]
Closing and re-opening to trigger github's status report
