### ISSUE TITLE
Dockerfile compile error: object CRC32C is not a member of package java.util.zip

### ISSUE THREAD

**Issue by darwin** [ACINQ/eclair#1113]
I'm trying to build Eclair in docker in [Simverse](https://github.com/darwin/simverse).

Git bisect pointed to 2f42538660779abf3f5594b670bb0b3632cb410a introduced compiler error `object CRC32C is not a member of package java.util.zip` [1].

It is probably caused by this: https://github.com/ACINQ/eclair/commit/2f42538660779abf3f5594b670bb0b3632cb410a#diff-094980f368988747a739b31df72815b8R19

I'm a Java noob. I tried to look for any changes in Dockerfiles on your side and didn't find anything where I got out of sync. Is this CRC32C a thing in older Java?

Observations:
1. Running `docker build .` from [tip](74af0304bd87f5cec93841d5181caffe3dfdb85d) of the eclair repo, fails in the same way
2. DockerHub CI builds [work](https://travis-ci.org/ACINQ/eclair/builds/578695813), because (I assume) they run on top of Java 11

[1] https://travis-ci.org/darwin/simverse/builds/578231444#L7799-L7805

**Comment by araspitzu** [comment]
I can confirm the docker build is broken because it uses an outdated JDK version to compile eclair (in which `java.util.zip.CRC32C` doesn't exist), thanks for reporting.
